- hosts: localhost
  tasks:
    - name: Change VMStore user password
      change_password:
        server: vmstore.vmlevel.com
        user: admin
        password: luns_suck
        newPassword: vm_aware
      register: result

    - debug: var=result
